config/routes.rb
require 'sidekiq/web'

Catarse::Application.routes.draw do
  match '/thank_you' => "static#thank_you"
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  check_user_admin = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user.admin }

  filter :locale, exclude: /\/auth\//

  # Mountable engines
  constraints check_user_admin do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount CatarsePaypalExpress::Engine  => "/", :as => :catarse_paypal_express
  mount CatarseMoip::Engine           => "/", :as => :catarse_moip

  # Non production routes
  if Rails.env.development?
    resources :emails, :only => [ :index ]
  end

  # Channels
  constraints subdomain: 'asas' do
    namespace :channels, path: '' do
      namespace :adm do
        resources :projects, only: [ :index, :update ] do
          member do
            put 'approve'
            put 'reject'
            put 'push_to_draft'
          end
        end
      end
      get '/', to: 'profiles#show', :as => :profile 
      get '/how-it-works', to: 'profiles#how_it_works', as: :about
      resources :projects, only: [:new, :create, :show] do
        collection do
          get 'video'
          get 'check_slug'
        end
      end
      resources :channels_subscribers, only: [:index, :create, :destroy]
    end
  end

  # Static Pages
  get '/sitemap',               to: 'static#sitemap',             as: :sitemap
  get '/guidelines',            to: 'static#guidelines',          as: :guidelines 
  get "/guidelines_tips",       to: "static#guidelines_tips",     as: :guidelines_tips
  get "/guidelines_backers",    to: "static#guidelines_backers",  as: :guidelines_backers
  get "/guidelines_start",      to: "static#guidelines_start",    as: :guidelines_start
  get "/about",                 to: "static#about",               as: :about
  get "/faq",                   to: "static#faq",                 as: :faq


  match "/explore" => "explore#index", :as => :explore
  match "/explore#:quick" => "explore#index", :as => :explore_quick
  match "/credits" => "credits#index", :as => :credits

  match "/reward/:id" => "rewards#show", :as => :reward
  resources :posts, only: [:index, :create]

  namespace :reports do
    resources :backer_reports_for_project_owners, only: [:index]
  end

  resources :projects do
    resources :updates, only: [ :index, :create, :destroy ]
    resources :rewards, only: [ :index, :create, :update, :destroy ]
    resources :backers, controller: 'projects/backers', only: [ :index, :show, :new, :create ] do
      member do
        match 'credits_checkout'
        post 'update_info'
      end
    end
    collection do
      get 'video'
      get 'check_slug'
    end
    member do
      put 'pay'
      get 'embed'
      get 'video_embed'
    end
  end
  resources :users do
    resources :backers, :only => [:index]
    resources :unsubscribes, :only => [:create]
    member do
      get 'projects'
      get 'credits'
      put 'unsubscribe_update'
      put 'update_email'
      put 'update_password'
    end
  end
  match "/users/:id/request_refund/:back_id" => 'users#request_refund'

  resources :credits, only: [:index] do
    collection do
      get 'buy'
      post 'refund'
    end
  end

  namespace :adm do
    resources :projects, only: [ :index, :update ] do
      member do
        put 'approve'
        put 'reject'
        put 'push_to_draft'
      end
    end

    resources :financials, only: [ :index ]

    resources :backers, only: [ :index, :update ] do
      member do
        put 'confirm'
        put 'unconfirm'
        put 'change_reward'
      end
    end
    resources :users, only: [ :index ]

    namespace :reports do
      resources :backer_reports, only: [ :index ]
    end
  end

  match "/mudancadelogin" => "users#set_email", as: :set_email_users
  match "/:permalink" => "projects#show", as: :project_by_slug

  # Root path
  root to: 'projects#index'

end

app/controllers/adm/projects_controller.rb
class Adm::ProjectsController < Adm::BaseController
  menu I18n.t("adm.projects.index.menu") => Rails.application.routes.url_helpers.adm_projects_path

  has_scope :by_id, :pg_search, :user_name_contains, :by_state
  has_scope :between_created_at, using: [ :start_at, :ends_at ], allow_blank: true
  has_scope :order_table, default: 'created_at'

  before_filter do
    @total_projects = Project.count
  end

  [:approve, :reject, :push_to_draft].each do |name|
    define_method name do
      @project = Project.find params[:id]
      @project.send("#{name.to_s}!")
      redirect_to :back
    end
  end

  def collection
    @projects = end_of_association_chain.page(params[:page])
  end
end

app/controllers/channels/adm/projects_controller.rb
class Channels::Adm::ProjectsController < Adm::BaseController
  menu I18n.t('channels.adm.menu') => Rails.application.routes.url_helpers.adm_projects_path

  
  has_scope :by_id, :pg_search, :user_name_contains, :order_table, :by_state
  has_scope :between_created_at, using: [ :start_at, :ends_at ], allow_blank: true
  has_scope :order_table do |controller, scope, value|
  value.present? ? scope.order_table(value) : scope.order('created_at DESC')
  end



  before_filter do
    @channel        =  Channel.find_by_permalink!(request.subdomain.to_s)
    @total_projects =  @channel.projects.size 
  end

  [:approve, :reject, :push_to_draft].each do |name|
    define_method name do
      @project    = @channel.projects.find(params[:id])
      @project.send("#{name.to_s}!")
      redirect_to :back
    end
  end

  protected
    def begin_of_association_chain
      @channel
    end

    def collection
      @projects = apply_scopes(@channel.projects.page(params[:page]))
    end
  

end

app/controllers/channels/projects_controller.rb
class Channels::ProjectsController < ProjectsController
  belongs_to :channel, finder: :find_by_permalink!, param: :profile_id


  # Inheriting from the original Projects controller
  # With one addition: we include the project into the current channel
  before_filter only: [:create] { params[:project][:channels] = [@channel] }
  after_filter only: [:create] { notify_trustees }

  prepend_before_filter{ params[:profile_id] = request.subdomain }




  # After a project submission through a channel, notify all channel's trustees
  protected
    def notify_trustees

    end
end

app/controllers/projects/backers_controller.rb
class Projects::BackersController < ApplicationController
  inherit_resources
  actions :index, :show, :new, :update_info, :review, :create
  skip_before_filter :force_http, only: [:create, :update_info]
  skip_before_filter :verify_authenticity_token, :only => [:moip]
  load_and_authorize_resource
  belongs_to :project

  def update_info
    resource.update_attributes(params[:backer])
    render :json => {:message => 'updated'}
  end

  def index
    @backers = parent.backers.confirmed.order("confirmed_at DESC").page(params[:page]).per(10)
    render :json => @backers.to_json(:can_manage => can?(:update, @project))
  end

  def show
    @title = t('projects.backers.show.title')
    session[:thank_you_backer_id] = nil
  end

  def new
    unless parent.online?
      flash[:failure] = t('projects.back.cannot_back')
      return redirect_to :root
    end

    @create_url = ::Configuration[:secure_review_host] ?
      project_backers_url(@project, {:host => ::Configuration[:secure_review_host], :protocol => 'https'}) :
      project_backers_path(@project)

    @title = t('projects.backers.new.title', :name => @project.name)
    @backer = @project.backers.new(:user => current_user)
    empty_reward = Reward.new(:id => 0, :minimum_value => 0, :description => t('projects.backers.new.no_reward'))
    @rewards = [empty_reward] + @project.rewards.order(:minimum_value)
    @reward = @project.rewards.find params[:reward_id] if params[:reward_id]
    @reward = nil if @reward and @reward.sold_out?
    if @reward
      @backer.reward = @reward
      @backer.value = "%0.0f" % @reward.minimum_value
    end
  end

  def create
    @title = t('projects.backers.create.title')
    @backer.reward_id = nil if params[:backer][:reward_id].to_s == '0'
    @backer.user = current_user
    create! do |success,failure|
      failure.html do
        flash[:failure] = t('projects.backers.review.error')
        return redirect_to new_project_backer_path(@project)
      end
      
      session[:thank_you_backer_id] = @backer.id      
      return render :create
    end
    @thank_you_id = @project.id
  end

  def credits_checkout
    if current_user.credits < @backer.value
      flash[:failure] = t('projects.backers.checkout.no_credits')
      return redirect_to new_project_backer_path(@backer.project)
    end

    unless @backer.confirmed
      @backer.update_attributes({ payment_method: 'Credits' })
      @backer.confirm!
    end
    flash[:success] = t('projects.backers.checkout.success')
    redirect_to project_backer_path(project_id: parent.id, id: resource.id)
  end
end

app/controllers/projects_controller.rb
# coding: utf-8
class ProjectsController < ApplicationController
  include ActionView::Helpers::DateHelper
  load_and_authorize_resource only: [ :new, :create, :update, :destroy ]

  inherit_resources
  has_scope :pg_search, :by_category_id, :recent, :expiring, :successful, :recommended, :not_expired
  respond_to :html, :except => [:backers]
  respond_to :json, :only => [:index, :show, :backers, :update]
  skip_before_filter :detect_locale, :only => [:backers]

  def index
    index! do |format|
      format.html do
        @title = t("site.title")
        collection_projects = Project.recommended_for_home
        unless collection_projects.empty?
          if current_user and current_user.recommended_project
            @recommended_project  ||= current_user.recommended_project
            collection_projects   ||= collection_projects.where("id != ? AND category_id != ?", 
                                                                current_user.recommended_project.id, 
                                                                @recommended_project.category_id)
          end
          @first_project, @second_project, @third_project, @fourth_project = collection_projects.all
        end

        project_ids = collection_projects.map{|p| p.id }
        project_ids << @recommended_project.id if @recommended_project

        @expiring = Project.expiring_for_home(project_ids)
        @recent   = Project.recent_for_home(project_ids)
        @blog_posts = blog_posts
      end

      format.json do
        @projects = apply_scopes(Project).visible.order_for_search
        respond_with(@projects.includes(:project_total, :user, :category).page(params[:page]).per(6))
      end
    end
  end

  def new
    new! do
      @title = t('projects.new.title')
      @project.rewards.build
    end
  end

  def create
    params[:project][:expires_at] += (23.hours + 59.minutes + 59.seconds) if params[:project][:expires_at]
    validate_rewards_attributes if params[:project][:rewards_attributes].present?

    @project = current_user.projects.new(params[:project])

    create!(:notice => t('projects.create.success')) do |success, failure|
      success.html{ return redirect_to project_by_slug_path(@project.permalink) }
    end
  end

  def show
    begin
      if params[:permalink].present?
        @project = Project.where("lower(permalink) = ?", params[:permalink].downcase).last
      else
        return redirect_to project_by_slug_path(resource.permalink)
      end

      show!{
        @title = @project.name
        @rewards = @project.rewards.includes(:project).order(:minimum_value).all
        @backers = @project.backers.confirmed.limit(12).order("confirmed_at DESC").all
        fb_admins_add(@project.user.facebook_id) if @project.user.facebook_id
        @update = @project.updates.where(:id => params[:update_id]).first if params[:update_id].present?
      }
    rescue ActiveRecord::RecordNotFound
      return render_404
    end
  end

  def video
    project = Project.new(:video_url => params[:url])
    if project.video
      render json: project.video.to_json
    else
      render json: {video_id: false}.to_json
    end
  end

  def check_slug
    project = Project.where("lower(permalink) = ?", params[:permalink].downcase)
    render :json => {:available => project.empty?}.to_json
  end

  def embed
    @project = Project.find params[:id]
    @title = @project.name
    render :layout => 'embed'
  end

  def video_embed
    @project = Project.find params[:id]
    @title = @project.name
    render :layout => 'embed'
  end

  def blog_posts
    Blog.fetch_last_posts.inject([]) do |total,item|
      total << item if total.size < 2
      total
    end
  rescue
    []
  end

  # Just to fix a minor bug,
  # when user submit the project without some rewards.
  def validate_rewards_attributes
    rewards = params[:project][:rewards_attributes]
    rewards.each do |r|
      rewards.delete(r[0]) unless Reward.new(r[1]).valid?
    end
  end
end

app/views/projects/_backer.html.slim
script type="text/template" id="empty_backers_template"
  p= t('projects.project_backers.empty')

script type="text/template" id="backers_template"
  ul.collection_list

script type="text/template" id="backer_template"
  .backer
    | <% if(anonymous) { %>
    img src="/assets/user.png" class="backer_avatar"
    .back_info
      p#text
        em.anon=" #{t('.anonymous_backer')}"
      p#confirmed
        | <%= confirmed_at %>
      p#backed= t('.anonymous_description')
    | <% } else { %>
    a href="<%= user['url'] %>"
      img src="<%= user['image'] %>" class="backer_avatar"
    .back_info
      p#text
        a href="<%= user['url'] %>"
         | <%= user['short_name'] %>
      p#confirmed
        | <%= confirmed_at %>
      p#backed
        | <%= user['backs_text'] %>
    | <% } %>
    - if current_user and (current_user == @project.user or current_user.admin)
      .reward
        =
        .value <%= value %> .
        | <% if (reward) { %>
        .user_reward <%= reward['display_minimum'] %> - <%= reward['medium_description'] %>
        | <% } else { %>
        | &nbsp;
        = t('.no_reward')
        | <% } %>
        | <% if(user['email']) { %>
        .user_email <%= user['email'] %>
        | <% } else { %>
        | &nbsp;
        = t('not_informed')
        |.
        | <% } %>
        
    .clear

app/views/projects/_box.html.slim
.project[itemscope itemtype="http://schema.org/CreativeWork" class=(custom_class if defined?(custom_class))]
  meta[itemprop="dateCreated" content=project.created_at.to_date]
  - if project.expired?
    .status_image
      = link_to project_by_slug_path(permalink: project.permalink), :target => ( defined?(embed_link) ? '__blank' : '' ) do
        - if project.successful?
          = image_tag "successful.#{I18n.locale}.png"
        - elsif project.waiting_funds?
          = image_tag "waiting_confirmation.#{I18n.locale}.png"
        - else
          = image_tag "not_successful.#{I18n.locale}.png"
  .box
    p.black_box= project.category
    .cover
      = link_to project, :target => ( defined?(embed_link) ? '__blank' : '' ) do
        = image_tag project.display_image, :itemprop => 'image'
    .project_content
      h4= link_to project, :target => ( defined?(embed_link) ? '__blank' : '' ), :itemprop => 'url' do
        span[itemprop="name"]= project.name
      p.author
        = t('.by')
        |&nbsp;
        span[itemprop="author"]= project.user.name
      p.description[itemprop="description"]= truncate(project.headline, :length => 140)
      p.where[itemprop="contentLocation"]
        - unless project.user.address_city.blank?
          = project.user.address_city
          - unless project.user.address_state.blank?
            | /
            = project.user.address_state
    .info_bar
      .status_bar
        .progress style="width: #{project.display_progress}%;"
      ul
        li
          - if project.in_time?
            h6= "#{project.time_to_go[:time]} #{project.time_to_go[:unit]}"
            p= "#{project.remaining_text}"
          - else
            h6= I18n.t("project.display_status.#{project.display_status}").capitalize
            p= project.display_expires_at
        li
          h6= "#{project.display_pledged}"
          p= "#{t('projects.project.backed')}"

        li
          h6= "#{project.progress}%"
          p= "#{t('projects.project.reached')}"

app/views/projects/_draft_warning.html.slim
br
#project_warning.bootstrap-alert
  .alert.alert-warning
    i ATENÇÃO!  Este projeto ainda não está no ar... Seja bem-vindo ao rascunho o/
    br/
    br/
    ' Este projeto ainda está em fase de Rascunho, isso significa que nenhuma informação abaixo é definitiva até a entrada do projeto no ar.
    | Por isso, aproveite! Dê uma olhada no vídeo, na descrição e nas recompensas e <strong> deixe seu feedback na aba de comentários.</strong>
    br/
    br/
    '<strong>Lembrando que:</strong> O Catarse é uma plataforma curada, o que significa que vamos avaliar o foco, a viabilidade, e a consistência do seu
    ' projeto durante o processo de Rascunho. Se entendermos que o seu projeto não está de acordo com os nossos
    = link_to 'Critérios de Seleção', 'http://docs.google.com/document/d/1Heh9LlvoSoD0lUfbmV5WlISJ3nqmGpEQiw15TBuCn-0/edit', target: '_blank'
    | , ele poderá ser recusado pela equipe de curadores.
    br/
    br/
    | Sinta-se a vontade pra nos enviar perguntas e feedbacks durante todo o processo =)
    br/
    ' Pra fazer isso acesse a nossa
    = link_to 'Central de Suporte', Configuration[:support_forum], target: '_blank'

app/views/projects/_project.html.slim
div class="curated_project #{(defined?(has_comments) ? :compost_project : '')}"
  = render 'projects/box', project: project, custom_class: (custom_class if defined?(custom_class))
  - if defined?(has_comments)
    .project_comment
      h3= "#{(defined?(comments_title) ? comments_title : project.category)}"
      p= "#{project.home_page_comment}"
  - if defined?(project_curated_page) and project_curated_page.count > 0 and project_curated_page.first.description.present?
    .project_curator_description
      == project_curated_page.first.description_html

app/views/projects/_recommended_header.html.slim
#recommended_header
  .resume_about
    = image_tag "catarse/box_#{I18n.locale}.jpg"
    .bootstrap-form
      = form_tag(guidelines_path, :method => :get, :id => 'guidelines_form') do
        fieldset
          .bootstrap-twitter
            .button
              = link_to t('.guidelines'), guidelines_path, :class=>'btn_explore'
              span = t('.guidelines_subtitle')
  .project_info
    - if current_user
      - if @recommended_project
        = render :partial => "project_header", :locals => {:title => t('projects.recommended_header.suggest_for_you'), :project => @recommended_project} if @recommended_project
      - else
        = render :partial => "project_header", :locals => {:title => t('projects.recommended_header.highlight_project'), :project => @fourth_project} if @fourth_project
    - else
      = render :partial => "project_header", :locals => {:title => t('projects.recommended_header.highlight_project'), :project => @fourth_project} if @fourth_project
  .clearfix

app/views/projects/_rejected_warning.html.slim
br
#project_warning.bootstrap-alert
  .alert.alert-warning
    i ATENÇÃO!  Este projeto foi rejeitado
    br/
    br/
    | Esse projeto não se enquadra aos nossos <a href='https://docs.google.com/document/d/1Heh9LlvoSoD0lUfbmV5WlISJ3nqmGpEQiw15TBuCn-0/edit' target='_blank'>critérios de seleção.</a>

app/views/projects/_show_embed.html.slim
- box_width = "240px"
- box_height = "415px"
- video_width = "384px"
- video_height = "415px"
#embed_overlay.overlay.hide
  #project_embed.hide
    a.close href='javascript:CATARSE.router.back()' X
    #project_box_embed
      iframe frameborder='0' height=box_height width=box_width src=embed_project_path(@project)
      form.html= text_area_tag 'project_box_embed_html', '<iframe frameborder="0" height="' + box_height + '" src="' + embed_project_url(@project) + '" width="' + box_width + '"></iframe>', :readonly => true
    #project_video_embed
      iframe frameborder='0' height=video_height width=video_width src=video_embed_project_path(@project)
      form.html= text_area_tag 'project_video_embed_html', '<iframe frameborder="0" height="' + video_height + '" src="' + video_embed_project_url(@project) + '" width="' + video_width + '"></iframe>', :readonly => true
    .clearfix

app/views/projects/_successful_warning.html.slim
br
#project_warning.bootstrap-alert
  .alert.alert-warning
    i Parabéns! Seu projeto foi  bem sucedido =D 
    br/
    br/
    | Comunicação é a chave de ouro pra fechar essa campanha ;)
    br/
    | Use a Aba de Novidades para compartilhar informações sobre o desenvolvimento do projeto e a entrega de recompensas.
    br/
    br/
    | As últimas semanas representaram uma troca, um contato e uma aproximação entre você e seu público, envolvendo assuntos delicados como carinho, 
    | expectativa, confiança e dinheiro.  Agora é hora de agradecer seus apoiadores, realizar o projeto e entregar as recompensas!!
    br/
    br/
    b Lembrando que: 
    | O repasse do dinheiro acontecerá da seguinte forma: O pagamento será feito em até 5 dias úteis após o prazo de encerramento do projeto. 
    | Assim que você receber o dinheiro na sua Conta Para Vendedores no MoIP e solicitar o saque, levarão no máximo 4 dias úteis para o dinheiro chegar 
    | na sua conta corrente. Confira: 
    = link_to 'Como será feito o repasse?', 'http://suporte.catarse.me/knowledgebase/articles/161090-como-ser%C3%A1-feito-o-repasse-do-dinheiro-', target: '_blank'
    br/
    br/
    | Sinta-se a vontade pra nos enviar perguntas e feedbacks durante todo o processo =) 
    br/
    | Pra fazer isso acesse a nossa  
    = link_to 'Central de Suporte', Configuration[:support_forum], target: '_blank'

app/views/projects/_waiting_funds_warning.html.slim
br
#project_warning.bootstrap-alert
  .alert.alert-warning
    i Acabou o prazo!
    br/
    br/
    | Durante 3 dias úteis após o fim do prazo, seu projeto estará aguardando a confirmação das contribuições de última hora.
    br/
    br/
    ' Caso seu projeto atinja a meta, o repasse do dinheiro acontecerá da seguinte forma:
    ' O pagamento será feito em até 5 dias úteis após o prazo de encerramento do projeto. Assim que você receber
    ' o dinheiro na sua Conta Para Vendedores no MoIP e solicitar o saque, levarão no máximo 4 dias úteis para o dinheiro
    ' chegar na sua conta corrente. Confira:
    = link_to 'Como será feito o repasse?', 'http://suporte.catarse.me/knowledgebase/articles/161090-como-ser%C3%A1-feito-o-repasse-do-dinheiro-', target: '_blank'
    br/
    br/
    ' Caso seu projeto não atinja a meta, todo dinheiro será devolvido aos apoiadores.
    ' A principio eles receberão de volta o valor da contribuição na forma de créditos para apoiar outros projetos
    ' na plataforma e receberão um e-mail com instruções sobre como pedir o estorno.
    ' Confira:
    = link_to 'Regras e Funcionamento dos Reembolsos', 'http://suporte.catarse.me/knowledgebase/articles/164746-regras-e-funcionamento-dos-reembolsos-estornos', target: '_blank'
    br/
    br/
    ' Caso o seu projeto tenha atingido pelo menos 30% da meta financeira você está apto a solicitar a a 2aChance. Confira:
    = link_to 'Regulamento da 2a Chance', 'http://suporte.catarse.me/knowledgebase/articles/161109-meu-projeto-n%C3%A3o-foi-financiado-posso-ter-uma-nova', target: '_blank'
    br/
    br/
    ' Sinta-se a vontade pra nos enviar perguntas e feedbacks durante todo o processo =)
    br/
    ' Pra fazer isso acesse a nossa
    = link_to 'Central de Suporte', Configuration[:support_forum], target: '_blank'

app/views/projects/embed.html.slim
#embed
  = render :partial => 'box', :locals => { :project => @project, :embed_link => true }

app/views/projects/index.html.slim
/ Temporaly using channels banner
  = render :partial => 'recommended_header'
= render :partial => 'channels/projects/banner'
#page_content
  .container
    .main
      .selected_projects.list
        .list_title
          .title
            h2= t('sections.selection.title')
        .projects
          = render :partial => 'project', :locals => {:project => @first_project, :custom_class => 'first' } if @first_project
          = render :partial => 'project', :locals => {:project => @second_project } if @second_project
          = render :partial => 'project', :locals => {:project => @third_project, :custom_class => 'last' } if @third_project
        .explore_link
          hr
          = link_to t('main.links.selected'), explore_path(anchor: :recommended)

      .expiring_projects.list
        .list_title
          .title
            h2= t('sections.expiring.title')
        .projects
          - @expiring.each_with_index do |item,i|
            == render 'project', :project => item, :custom_class => ((@expiring.length == (i+1) ? 'last' : false) || (i==0 ? 'first' : false))
        .explore_link
          hr
          = link_to t('main.links.expiring'), explore_path(anchor: :expiring)

      .recents_projects.list
        .list_title
          .title
            h2= t('sections.recents.title')
        .projects
          - @recent.each_with_index do |item,i|
            == render 'project', :project => item, :custom_class => ((@recent.length == (i+1) ? 'last' : false) || (i==0 ? 'first' : false))
        .explore_link
          hr
          = link_to t('main.links.recents'), explore_path(anchor: :recent)

    .sidebar
      .content
        .blog
          h3= t('sidebar.titles.blog')
          ul.posts
            - @blog_posts.each do |post|
              li
                h2
                  = link_to post.url, target: '__blank' do
                    /= image_tag("catarse/post_title_image.png")
                    = truncate(post.title, length: 80)
                p.author= "#{t('projects.box.by')} #{post.author}"
                = link_to post.url, target: '__blank', class: 'resume' do
                  = truncate(post.summary, length: 130).html_safe

        .facebook
          h3= t('sidebar.titles.facebook')
          .fb-like data-href="#{Configuration['facebook_url']}" data-send="false" data-width="160" data-show-faces="true"
        #twitter.twitter[data-username="@#{Configuration['twitter_username']}"]
        .newsletter
          h3= t('sidebar.titles.newsletter')
          = form_tag Configuration['mailchimp_url'], id: 'mailee-form', method: 'post' do
            = text_field_tag 'EMAIL', nil, placeholder: 'email@email.com', label: 'email'
            = submit_tag t('sidebar.buttons.newsletter')
    .clearfix