config/routes.rb
require 'sidekiq/web'

Catarse::Application.routes.draw do
  match '/thank_you' => "static#thank_you"
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  check_user_admin = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user.admin }

  filter :locale, exclude: /\/auth\//

  # Mountable engines
  constraints check_user_admin do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount CatarsePaypalExpress::Engine  => "/", :as => :catarse_paypal_express
  mount CatarseMoip::Engine           => "/", :as => :catarse_moip

  # Non production routes
  if Rails.env.development?
    resources :emails, :only => [ :index ]
  end

  # Channels
  constraints subdomain: 'asas' do
    namespace :channels, path: '' do
      namespace :adm do
        resources :projects, only: [ :index, :update ] do
          member do
            put 'approve'
            put 'reject'
            put 'push_to_draft'
          end
        end
      end
      get '/', to: 'profiles#show', :as => :profile 
      get '/how-it-works', to: 'profiles#how_it_works', as: :about
      resources :projects, only: [:new, :create, :show] do
        collection do
          get 'video'
          get 'check_slug'
        end
      end
      resources :channels_subscribers, only: [:index, :create, :destroy]
    end
  end

  # Static Pages
  get '/sitemap',               to: 'static#sitemap',             as: :sitemap
  get '/guidelines',            to: 'static#guidelines',          as: :guidelines 
  get "/guidelines_tips",       to: "static#guidelines_tips",     as: :guidelines_tips
  get "/guidelines_backers",    to: "static#guidelines_backers",  as: :guidelines_backers
  get "/guidelines_start",      to: "static#guidelines_start",    as: :guidelines_start
  get "/about",                 to: "static#about",               as: :about
  get "/faq",                   to: "static#faq",                 as: :faq


  match "/explore" => "explore#index", :as => :explore
  match "/explore#:quick" => "explore#index", :as => :explore_quick
  match "/credits" => "credits#index", :as => :credits

  match "/reward/:id" => "rewards#show", :as => :reward
  resources :posts, only: [:index, :create]

  namespace :reports do
    resources :backer_reports_for_project_owners, only: [:index]
  end

  resources :projects do
    resources :updates, only: [ :index, :create, :destroy ]
    resources :rewards, only: [ :index, :create, :update, :destroy ]
    resources :backers, controller: 'projects/backers', only: [ :index, :show, :new, :create ] do
      member do
        match 'credits_checkout'
        post 'update_info'
      end
    end
    collection do
      get 'video'
      get 'check_slug'
    end
    member do
      put 'pay'
      get 'embed'
      get 'video_embed'
    end
  end
  resources :users do
    resources :backers, :only => [:index]
    resources :unsubscribes, :only => [:create]
    member do
      get 'projects'
      get 'credits'
      put 'unsubscribe_update'
      put 'update_email'
      put 'update_password'
    end
  end
  match "/users/:id/request_refund/:back_id" => 'users#request_refund'

  resources :credits, only: [:index] do
    collection do
      get 'buy'
      post 'refund'
    end
  end

  namespace :adm do
    resources :projects, only: [ :index, :update ] do
      member do
        put 'approve'
        put 'reject'
        put 'push_to_draft'
      end
    end

    resources :financials, only: [ :index ]

    resources :backers, only: [ :index, :update ] do
      member do
        put 'confirm'
        put 'unconfirm'
        put 'change_reward'
      end
    end
    resources :users, only: [ :index ]

    namespace :reports do
      resources :backer_reports, only: [ :index ]
    end
  end

  match "/mudancadelogin" => "users#set_email", as: :set_email_users
  match "/:permalink" => "projects#show", as: :project_by_slug

  # Root path
  root to: 'projects#index'

end

app/models/channel.rb
class Channel < ActiveRecord::Base
  attr_accessible :description, :name, :permalink
  schema_associations

  validates_presence_of :name, :description, :permalink
  validates_uniqueness_of :permalink

  has_and_belongs_to_many :projects
  has_and_belongs_to_many :subscribers
  has_and_belongs_to_many :trustees, class_name: :User, join_table: :channels_trustees


  delegate :all, to: :decorator


  # Links to channels should be their permalink
  def to_param; self.permalink end
  

  # Using decorators
  def decorator
    @decorator ||= ChannelDecorator.new(self)
  end
end

app/controllers/channels/adm/projects_controller.rb
class Channels::Adm::ProjectsController < Adm::BaseController
  menu I18n.t('channels.adm.menu') => Rails.application.routes.url_helpers.adm_projects_path

  
  has_scope :by_id, :pg_search, :user_name_contains, :order_table, :by_state
  has_scope :between_created_at, using: [ :start_at, :ends_at ], allow_blank: true
  has_scope :order_table do |controller, scope, value|
  value.present? ? scope.order_table(value) : scope.order('created_at DESC')
  end



  before_filter do
    @channel        =  Channel.find_by_permalink!(request.subdomain.to_s)
    @total_projects =  @channel.projects.size 
  end

  [:approve, :reject, :push_to_draft].each do |name|
    define_method name do
      @project    = @channel.projects.find(params[:id])
      @project.send("#{name.to_s}!")
      redirect_to :back
    end
  end

  protected
    def begin_of_association_chain
      @channel
    end

    def collection
      @projects = apply_scopes(@channel.projects.page(params[:page]))
    end
  

end

app/controllers/channels/base_controller.rb
class Channels::BaseController < ApplicationController
  skip_before_filter :set_locale
  before_filter do
    I18n.locale = 'pt'
  end
end

app/controllers/channels/channels_subscribers_controller.rb
class Channels::ChannelsSubscribersController < Channels::BaseController
  inherit_resources
  load_and_authorize_resource
  actions :index, :create, :destroy

  # we skid the set_locale because we are using the index method to create a record
  skip_before_filter :set_locale

  def create
    begin
      create! do |success,failure|
        success.html{ 
          flash[:notice] = I18n.t('channels_subscribers.created')
          return redirect_to root_path }
      end
    rescue PG::Error, ActiveRecord::RecordNotUnique => e
      return redirect_to root_path
    end
  end
  alias_method :index, :create

  def destroy
    destroy! do |success,failure|
      success.html{ 
        flash[:notice] = I18n.t('channels_subscribers.deleted')
        return redirect_to root_path 
      }
    end
  end

  prepend_before_filter do
    params[:channels_subscriber] = { channel_id: Channel.find_by_permalink!(request.subdomain).id, user_id: current_user.id } if current_user
  end
end

app/controllers/channels/profiles_controller.rb
class Channels::ProfilesController < Channels::BaseController
  inherit_resources
  defaults resource_class: Channel, finder: :find_by_permalink! 
  actions :show
  custom_actions resource: [:how_it_works]



  before_filter{ params[:id] = request.subdomain }

end

app/controllers/channels/projects_controller.rb
class Channels::ProjectsController < ProjectsController
  belongs_to :channel, finder: :find_by_permalink!, param: :profile_id


  # Inheriting from the original Projects controller
  # With one addition: we include the project into the current channel
  before_filter only: [:create] { params[:project][:channels] = [@channel] }
  after_filter only: [:create] { notify_trustees }

  prepend_before_filter{ params[:profile_id] = request.subdomain }




  # After a project submission through a channel, notify all channel's trustees
  protected
    def notify_trustees

    end
end

app/helpers/channels/base_helper.rb
module Channels::BaseHelper
end

app/views/channels/profiles/_footer.html.slim
#page_content.channel_footer
  .container
    nav
      = link_to t('channels.footer.terms'), 'http://suporte.catarse.me/knowledgebase/articles/190852-termo-de-uso-canal-asas', title: t('channels.footer.terms'), target: '_blank'
      .separator
      = link_to t('channels.footer.privacy_policy'), 'http://suporte.catarse.me/knowledgebase/articles/161103-pol%C3%ADtica-de-privacidade', title: t('channels.footer.privacy_policy'), target: '_blank' 
      .separator
      = link_to t('channels.footer.how_it_works', name: @profile.name), channels_about_path, title: t('channels.footer.how_it_works', name: @profile.name), target: '_blank' 
      .separator
      = mail_to @profile.email, t('channels.footer.contact'), title: t('channels.footer.contact'), target: '_blank' 
      .separator
      = link_to t('channels.footer.how_channels_work'), 'http://blog.catarse.me/conheca-os-canais-do-catarse/', title: t('channels.footer.how_channels_work'), target: '_blank' 

app/views/channels/profiles/how_it_works.html.slim
= content_for(:title, t('channels.how_it_works.title', channel: @profile.name))

#how_it_works.channels
  #page_content.projects
    .container
      h1 O Instituto Asas quer dar asas pra quem quer mudar o mundo.
      hr
      p.headline
        | Queremos inspirar, impulsionar e conectar jovens que querem transformar o mundo. 
        | Acreditamos que jovens com projetos transformadores precisam de mais oportunidades de formação, 
        | de maior articulação em rede, de espaço para dar visibilidade a suas iniciativas e também, 
        | de 
        strong acesso a investimento para seus projetos 


      .explanation
        .first
          h2 Empurrão inicial - Dicas
          p
            | Para começar 
            strong daremos dicas 
            | de como 
            strong estruturar e potencializar 
            | sua campanha de crowdfunding para obter melhores resultados.
        .last
          h2 Empurrão final - Gatilho
          p
            | Depois que o projeto estiver no ar, você mobiliza a sua rede e 
            strong quando alcançar 80% da sua meta, o Instituto Asas coloca os outros 20% 
            | pra garantir o sucesso da sua campanha.


  #page_content.how_to_participate
    .container
      .how
        .first
          h2 Para participar
          ul.topics
            li 
              | Entender como funciona o Catarse pois  o que vale pro Catarse, vale pro Canal Asas. Caso você seja novo por aqui, entre nesse link e 
              = link_to 'saiba mais', 'http://suporte.catarse.me/knowledgebase', target: '_blank' 
              |. 
            li Ter entre 18 e 29 anos
            li O seu projeto precisa promover algum tipo de impacto positivo na sociedade 
            li Você precisa emitir um recibo referente ao aporte do Instituto Asas 

        .last
          h2 Últimos detalhes
          ul.topics
            li Assim como qualquer outro apoiador do seu projeto, o Instituto Asas terá direito à recompensa de acordo com o valor aportado.
            li Caso você queira utilizar a marca do Instituto Asas, deverá seguir as regras do uso da marca.
            li No fim do ano, vamos realizar um encontro para conhecê-lo e para que você interaja com outros jovens transformadores.
          .if_your_project
            p 
              | Se o seu projeto já está no Catarse e você quer fazer parte deste 
              | Canal, envie pra gente: 
              = mail_to "canalasas@catarse.me"




  #page_content.send_your_project
    span
      | Você tem o perfil que procuramos? 
      = link_to t('channels.send_your_project'), new_project_path, class: [:ch_button, :ch_button_ok, :ch_button_green], title: t('channels.accessibility.send_your_project')

= render 'footer'

app/views/channels/profiles/show.html.slim
= content_for :title, @profile.name

#page_content.presentation
  .container
    .video
      .padding        
        //= image_tag('channels/capa_asas.jpg', title: @profile.name)
        = content_tag(:iframe, nil, src: 'http://player.vimeo.com/video/65078606?title=0&byline=0&portrait=0')
    .about
      h1              = @profile.name
      p.description   = truncate(@profile.description, length: 210)
      strong.headline = t('channels.projects.see_how_it_works')
      p.buttons       = link_to t('channels.projects.how_it_works'), channels_about_path, class: [:ch_button, :ch_button_ok, :ch_button_green], title: t('channels.accessibility.how_it_works') 
    .clearfix

#page_content.projects
  .container
    .channel
      .info
        .padding
          .image  = image_tag @profile.image, size: '195x120', title: @profile.name
          h3      = @profile.name
          span    = t('channels.curator')
          .social
            = link_to '', @profile.twitter, title: t('channels.accessibility.link_to_twitter'), class: [:"icon-twitter"] if @profile.twitter
            = link_to '', @profile.facebook, title: t('channels.accessibility.link_to_facebook'), class: [:"icon-facebook"] if @profile.facebook
            = link_to '', @profile.website, title: t('channels.accessibility.link_to_website'), class: [:"icon-earth"] if @profile.website

        hr
        .mail
          = mail_to @profile.email, t('channels.send_a_email'), class: ["icon-mail"], title: t('channels.send_a_email') 
      .subscription
        hr.before_subscribe
        - subscription = current_user.channels_subscribers.where(channel_id: resource.id).first rescue nil
        - if subscription
          = link_to channels_channels_subscriber_path(subscription.id), {method: :delete, class: [:ch_button, :ch_button_ok, :ch_button_unsubscribe, :ch_button_gray, :subscribe]} do
            .following= t('channels.following')
            .stop_following= t('channels.unfollow')
        - else
          = link_to t('channels.follow'), channels_channels_subscribers_path, method: :post, class: [:ch_button, :ch_button_ok, :ch_button_pink, :subscribe], title: t('channels.follow')
        .subscribes_count[title=t('channels.subscribed', count: @profile.channels_subscribers.size)]
          = resource.channels_subscribers.size

    ol.projects_list
      = content_tag_for(:li, @profile.projects.visible) do |project|
        = render partial: 'channels/projects/project', locals: { project: project }

= render 'footer'